org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.20.6
minecraft_version_range=[1.20.2,1.21)
legacy_minecraft_version_range=[1.20.1,1.21)
neo_version=20.6.139
neo_version_range=[20.2,)
loader_version_range=[1,)

mod_id=always_drop_loot
mod_name=Always Drop Loot
mod_license=Apache-2.0
mod_version=5.6.0+mc1.20-neoforge
mod_group_id=me.sargunvohra.mcmods
mod_authors=OneDefauter
mod_description=Make mobs always drop experience and loot, regardless of the cause of death.
