org.gradle.jvmargs=-Xmx4G
org.gradle.caching=false
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn
net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
forge_version=51.0.33
forge_version_range=[51,)
loader_version_range=[51,)
mod_id=always_drop_loot
mod_name=Always Drop Loot
mod_license=Apache-2.0
mod_version=5.6.0+mc1.21-forge
mod_group_id=me.sargunvohra.mcmods
mod_authors=OneDefauter
mod_description=Make mobs always drop experience and loot, regardless of the cause of death.
