org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.59
neo_version_range=[26.2.0,)

mod_id=always_drop_loot
mod_name=Always Drop Loot
mod_license=Apache-2.0
mod_version=5.6.0+mc26.2-neoforge
mod_group_id=me.sargunvohra.mcmods
mod_authors=OneDefauter
mod_description=Make mobs always drop experience and loot, regardless of the cause of death.
